### ISSUE TITLE
maven 无法引入插件

### ISSUE THREAD

**Issue by ttbadr** [bihe0832/Gradle-Dependencies-Check#3]
按照首页文档引入插件有问题，我看插件放在Android目录下面了https://repo1.maven.org/maven2/com/bihe0832/android/GradleDependenciesCheck/

**Comment by bihe0832** [comment]
抱歉哈，之前没关注这个project，所以没发现有个issue。

当时调整了仓库，Demo里面修改了，文档漏了没改，已经同步修改了。

再次感谢你的反馈~
